# Generated by Django 5.2.14 on 2026-05-07 22:37

import ckeditor.fields
import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('praenomen', models.CharField(blank=True, db_index=True, max_length=1000, null=True)),
                ('nomen', models.CharField(blank=True, db_index=True, max_length=1000, null=True)),
                ('cognomen', models.CharField(blank=True, db_index=True, max_length=1000, null=True)),
                ('agnomen', models.CharField(blank=True, db_index=True, max_length=1000, null=True)),
            ],
            options={
                'ordering': [django.db.models.functions.text.Upper('cognomen'), django.db.models.functions.text.Upper('nomen'), 'id'],
            },
        ),
        migrations.CreateModel(
            name='CiceroAsSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', ckeditor.fields.RichTextField()),
                ('name_clean', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'cicero as source',
                'ordering': [django.db.models.functions.text.Upper('name'), 'id'],
            },
        ),
        migrations.CreateModel(
            name='CitizenStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', ckeditor.fields.RichTextField()),
                ('name_clean', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'citizen statuses',
            },
        ),
        migrations.CreateModel(
            name='CourtType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', ckeditor.fields.RichTextField()),
                ('name_clean', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': [django.db.models.functions.text.Upper('name'), 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Orator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=1000)),
            ],
            options={
                'ordering': [django.db.models.functions.text.Upper('name'), 'id'],
            },
        ),
        migrations.CreateModel(
            name='OratoricalExemplumType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', ckeditor.fields.RichTextField()),
                ('name_clean', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': [django.db.models.functions.text.Upper('name'), 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OratorInCiceroBrutusType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', ckeditor.fields.RichTextField()),
                ('name_clean', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'orators in cicero brutus types',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SpeechType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', ckeditor.fields.RichTextField()),
                ('name_clean', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': [django.db.models.functions.text.Upper('name'), 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TimePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', ckeditor.fields.RichTextField()),
                ('name_clean', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': [django.db.models.functions.text.Upper('name'), 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', ckeditor.fields.RichTextField()),
                ('name_clean', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': [django.db.models.functions.text.Upper('name'), 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VenueType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', ckeditor.fields.RichTextField()),
                ('name_clean', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': [django.db.models.functions.text.Upper('name'), 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OratorInCiceroBrutus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('presented_as_an_orator', models.BooleanField(default=False)),
                ('not_in_sumners_register', models.BooleanField(default=False, verbose_name="Not in Sumner's register")),
                ('greek_orators_in_sumner', models.BooleanField(default=False)),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orators_in_cicero_brutus', to='researchdata.oratorincicerobrutustype')),
            ],
            options={
                'verbose_name_plural': 'orators in cicero brutus',
                'ordering': [django.db.models.functions.text.Upper('name'), 'id'],
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=1000)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='works', to='researchdata.author')),
            ],
            options={
                'ordering': [django.db.models.functions.text.Upper('name'), 'id'],
            },
        ),
        migrations.CreateModel(
            name='Passage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=1000)),
                ('name_ordering', models.TextField(blank=True, null=True)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='passages', to='researchdata.work')),
            ],
            options={
                'ordering': [django.db.models.functions.text.Upper('name_ordering'), 'id'],
            },
        ),
        migrations.CreateModel(
            name='OratorInPassage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_summary', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('speeches', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('content', models.BooleanField(default=False)),
                ('context', models.BooleanField(default=False)),
                ('athens', models.BooleanField(default=False, verbose_name='Athens (democratic)')),
                ('non_magistrate_senator', models.BooleanField(default=False, verbose_name='non-magistrate senator')),
                ('precise_date', models.CharField(blank=True, max_length=1000, null=True)),
                ('precise_date_order', models.IntegerField(blank=True, help_text='Number used to sort records by precise date, BC = negative, AD = positive', null=True)),
                ('court_type_details', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('liminal_speaker_non_elite', models.BooleanField(default=False)),
                ('liminal_speaker_non_roman', models.BooleanField(default=False)),
                ('liminal_speaker_women', models.BooleanField(default=False)),
                ('oratorical_exemplum', models.BooleanField(default=False)),
                ('cicero_work_used', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('research_notes', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('published', models.BooleanField(default=True, help_text='Uncheck this box to hide this record on the public interface')),
                ('cicero_as_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orators_in_passages', to='researchdata.ciceroassource')),
                ('citizen_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orators_in_passages', to='researchdata.citizenstatus')),
                ('court_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orators_in_passages', to='researchdata.courttype')),
                ('orator', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='orators_in_passages', to='researchdata.orator')),
                ('oratorical_exemplum_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orators_in_passages', to='researchdata.oratoricalexemplumtype')),
                ('passage', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='orators_in_passages', to='researchdata.passage')),
                ('speech_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orators_in_passages', to='researchdata.speechtype')),
                ('time_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orators_in_passages', to='researchdata.timeperiod')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orators_in_passages', to='researchdata.venue')),
                ('venue_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orators_in_passages', to='researchdata.venuetype')),
            ],
            options={
                'verbose_name_plural': 'orators in passages',
                'ordering': ['passage', 'orator', 'id'],
                'constraints': [models.UniqueConstraint(fields=('passage', 'orator'), name='unique_passage_per_orator')],
            },
        ),
    ]
